input_data_path: "data/raw/heart_cleveland_upload.csv"
output_model_path: "saved_models/tuned_model.pkl"
target_column: "condition"
split_test_size: 0.25
split_stratification: True
randomized_search_iters: 20
cv_n_folds: 5
random_seed: 2022
tuning_grid:
  RandomForestClassifier:
    max_depth: [ 2, 3, 5 ]
    n_estimators: [ 50, 100, 150 ]
    bootstrap: [ True, False ]
    criterion: [ "gini", "entropy" ]
  SVC:
    C: [ 1, 3, 9, 27 ]
    tol: [ 1e-2, 1e-3, 1e-4 ]
    kernel: [ "linear", "rbf", "sigmoid" ]
    shrinking: [ True, False ]
  AdaBoostClassifier:
    n_estimators: [ 50, 100, 150 ]
    algorithm: [ "SAMME", "SAMME.R" ]
    learning_rate: [ 0.8, 1, 1.2 ]